---
- name: Configurar máquinas
  hosts: vault-01
  user: root
  tags: 
    - setup
  roles:
    - configure-host

- name: Deploy Vault
  hosts: vault-01
  remote_user: vagrant
  tags:
    - vault
  roles:
    - vault
