Vagrant.configure("2") do |config|
    config.vm.hostname = "vault"
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.network "private_network", ip: "192.168.10.2"

    config.vm.provision "shell", inline: <<-SHELL
    echo "Ambiente para testes" > /tmp/vagrant.txt
  SHELL

  #Virtualbox Settings
  config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "server-vault"
      vb.memory = "1024"
      vb.cpus = "2"

  end
    config.vm.provision:shell, path: "bootstrap.sh"
end
