---
- name: Remover versões legadas do docker
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io

- name: Adicionar chave gpg para o apt
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: Adicionar repositório apt do docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true

- name: Instalar containerd 1.2.13-2
  apt:
    name: containerd.io=1.2.13-2
    state: present
    update_cache: yes
    force: true

- name: Instalar docker-ce 5:19.03.11
  apt:
    name:
      - "docker-ce=5:19.03.11~3-0~{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}"
      - "docker-ce-cli=5:19.03.11~3-0~{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}"
    state: present
    force: True

- name: Configurar hold dos pacotes
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Instalar pip
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    # - python-pip
    - python3-pip

- name: Instalar python-docker 
  pip:
    name: docker
    state: present

# - name: Instalar pacote pip docker-py
#   pip:
#     name: docker-py>=1.10.0'
#     state: absent

# - name: Copiar template do daemon.json
#   template:
#     src: templates/daemon.json.j2
#     dest: /etc/docker/daemon.json

- name: Restartar serviço do docker
  service:
    name: docker
    enabled: yes
    state: restarted
    daemon_reload: yes